name: Package and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set version from tag
        id: vars
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Prepare Addon Folder
        run: |
          mkdir SharedMedia_Quazii
          cp SharedMedia_Quazii.toc Quazii.lua SharedMedia_Quazii/
          cp -r font sound statusbar SharedMedia_Quazii/

      - name: Zip Addon
        run: |
          zip -r SharedMedia_Quazii-${{ env.RELEASE_VERSION }}-release.zip SharedMedia_Quazii

      - name: Upload Release Assetimage.png
        uses: softprops/action-gh-release@v2
        with:
          files: SharedMedia_Quazii-${{ env.RELEASE_VERSION }}-release.zip
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 